// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aysqzemlnjddoclgwtjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5c3F6ZW1sbmpkZG9jbGd3dGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzY5NDQsImV4cCI6MjA3MjcxMjk0NH0.LsRuWLNiqDGGCSWoVzvWPcO9yAu3QyNrZGh2ls5ZX_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});